sudo: required

language:
    - c

services:
    - docker

before_install:
    - docker pull liberforce/gtk3:mageia6

script:
  - docker run -v $(pwd):/home/testuser/$(basename $(pwd)) liberforce/gtk3:mageia6 /bin/sh -c "cd metrognome && mkdir builddir && meson builddir && ninja -C builddir && ninja -C builddir install"
