language: c
addons:
    apt:
        packages:
        - libgtk-3-dev
        - libgstreamer1.0-dev

install:
    - pip3 install meson

script:
    - mkdir builddir
    - meson builddir
    - ninja -C builddir
    - ninja -C builddir install
    - ninja -C builddir test
